apiVersion: apps/v1
kind: Deployment
metadata:
  name: ""
spec:
  selector:
    matchLabels:
      app: ""
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ""
    spec:
      containers:
      - args:
        - start-dev
        imagePullPolicy: Always
        name: keycloak
        ports:
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8080
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - curl --head --fail --silent http://127.0.0.1:8080/health/live
          periodSeconds: 1
        readinessProbe:
          exec:
            command:
              - curl --head --fail --silent http://127.0.0.1:8080/health/ready
          periodSeconds: 1
          failureThreshold: 180
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
